from django.urls import path, re_path
from django.views.decorators.csrf import csrf_exempt
from .views import *


urlpatterns = [
                path('', Index.as_view(), name='index'),
                path('search/', Search.as_view(), name='search'),
                path('blog/', News_all.as_view(), name='blog'),
                path('news/<slug:news_slug>/', ShowNews.as_view(), name='news'),
                path('fdocs-gia11/', Fdocs_gia11.as_view(), name='fdocs_gia11'),
                path('rdocs-gia11/', Rdocs_gia11.as_view(), name='rdocs_gia11'),
                path('guidelines-gia11/', Guidelines_gia11.as_view(), name='guidelines_gia11'),
                path('fdocs-gia9/', Fdocs_gia9.as_view(), name='fdocs_gia9'),
                path('rdocs-gia9/', Rdocs_gia9.as_view(), name='rdocs_gia9'),
                path('guidelines-gia9/', Guidelines_gia9.as_view(), name='guidelines_gia9'),
                path('sobes-gia9/', Sobes_gia9.as_view(), name='sobes_gia9'),
                path('info-gia9/', Info_gia9.as_view(), name='info_gia9'),
                path('raspisanie-gia9/', Raspisanie_gia9.as_view(), name='raspisanie_gia9'),
                path('obrazcy-blankov-gia9/', Obrazcy_blankov_gia9.as_view(), name='obrazcy_blankov_gia9'),
                path('specz-usloviya-gia9/', Specz_usloviya_gia9.as_view(), name='specz_usloviya_gia9'),
                path('podgotovka-kadrov_gia9/', Podgotovka_kadrov_gia9.as_view(), name='podgotovka_kadrov_gia9'),
                path('presentation-gia11/', Presentation_gia11.as_view(), name='presentation_gia11'),
                path('info-gia11/', Info_gia11.as_view(), name='info_gia11'),
                path('raspisanie-gia11/', Raspisanie_gia11.as_view(), name='raspisanie_gia11'),
                path('obrazcy-blankov-gia11/', Obrazcy_blankov_gia11.as_view(), name='obrazcy_blankov_gia11'),
                path('specz-usloviya-gia11/', Specz_usloviya_gia11.as_view(), name='specz_usloviya_gia11'),
                path('podgotovka-kadrov-gia11/', Podgotovka_kadrov_gia11.as_view(), name='podgotovka_kadrov_gia11'),
                path('training-events/', Training_events.as_view(), name='training_events'),
                path('training-events-general-info/', Training_events_general_info.as_view(), name='training_events_general_info'),
                path('fdocs-education-quality-assessment/', Fdocs_education_quality_assessment.as_view(), name='fdocs_education_quality_assessment'),
                path('rdocs-education-quality-assessment/', Rdocs_education_quality_assessment.as_view(), name='rdocs_education_quality_assessment'),
                path('testing-work/', Testing_work.as_view(), name='testing_work'),
                path('other-studies/', Other_studies.as_view(), name='other_studies'),
                path('activity/', Activity.as_view(), name='activity'),
                path('hotline/', Hotline.as_view(), name='hotline'),
                path('webinars/', Webinars.as_view(), name='webinars'),
            	path('constituent-documents/', Constituent_documents.as_view(), name='constituent_documents'),
                path('local-acts/', Local_acts.as_view(), name='local_acts'),
                path('services/', Services.as_view(), name='services'),
                path('contacts/', Contacts.as_view(), name='contacts'),
                path("robots.txt", RobotsTxtView.as_view()),
                path("sitemapxml.html", SitemapXmlView.as_view()),
                path("yandex_231c829d9a86caa9.html", YandexView.as_view()),
                path('update/', update_csv_data_view, name='update'),
]
